version: '3'
services:
  #授权服务
  mogu_data:
    image: registry.cn-shenzhen.aliyuncs.com/mogublog/nginx
    container_name: mogu_data
    restart: always
    ports:
      - 8001:8001
      - 8600:8600
    networks:
      - mushroom
    volumes:
      - ../data/mogu_data/:/home/mogu_blog/mogu_data/
      - ../config/mogu_data.conf:/etc/nginx/conf.d/default.conf
networks:
  mushroom:
    external: true
